MVCProject/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCProject.Controllers
{
    public class DashBoardController : Controller
    {


        [Route("Dashboard")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCProject/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCProject.Models;
using MVCProject.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProject.Controllers
{
    
    public class InstructorController : Controller
    {
        public IInstructorService InsRepo { get; }
        public ITrackService TrackRepo { get; }
        public UserManager<IdentityUser> UserManager { get; }
        public SignInManager<IdentityUser> SignInManager { get; }
        public RoleManager<IdentityRole> RoleManager { get; }
        public InstructorController(IInstructorService _InsRepo,
            ITrackService _TrackRepo, UserManager<IdentityUser> _UserManager,
            SignInManager<IdentityUser> _SignInManager, RoleManager<IdentityRole> _RoleManager)
        {
            InsRepo = _InsRepo;
            TrackRepo = _TrackRepo;
            UserManager = _UserManager;
            SignInManager = _SignInManager;
            RoleManager = _RoleManager;
        }



        [Authorize(Roles = "admin")]
        public IActionResult GetAll()
        {
            ViewData["trackName"] = TrackRepo.GetAll();
            return View(InsRepo.GetAll());
        }
        public IActionResult GetById([FromRoute] int id)
        {
            return View(InsRepo.GetById(id));
        }

        public IActionResult NameExit(string Name, int id)
        {
            Instructor ins = InsRepo.GetByName(Name);
            if (id == 0)   //add
            {
                if (ins == null)
                    return Json(true);
                return Json(false);
            }
            else           //edit
            {
                if (ins == null)
                    return Json(true);
                else
                {
                    if (ins.Id == id)
                        return Json(true);
                    return Json(false);
                }
            }
        }

        public IActionResult GetInstInTrack([FromRoute] int id)
        {
            ViewBag.tracks = TrackRepo.GetAll();
            List<Instructor> gModel = InsRepo.GetAllInstById(id);
            return PartialView("_GetInstInTrack", gModel);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            //user.Include(u => u.Roles)
            ViewData["listOfUser"] = await UserManager.GetUsersInRoleAsync("instructor");
            ViewBag.tracks = TrackRepo.GetAll();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Instructor newstd)
        {
            if (ModelState.IsValid)
            {
                InsRepo.Create(newstd);
                return RedirectToAction("GetAll");
            }
            ViewData["tracks"] = TrackRepo.GetAll();
            return View(newstd);
        }



        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewBag.tracks = TrackRepo.GetAll();
            Instructor std = InsRepo.GetById(id);
            return View(std);
        }
        [HttpPost]
        public IActionResult Update(Instructor newins)
        {
            if (ModelState.IsValid)
            {
                InsRepo.Update(newins);
                return RedirectToAction("GetAll");
            }
            ViewBag.tracks = TrackRepo.GetAll();
            return View(newins);

        }
        public IActionResult Delete([FromRoute] int id)
        {
            try
            {
                InsRepo.Delete(id);
                return RedirectToAction("GetAll");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                return View();
            }
        }



    }
}

MVCProject/Controllers/StudentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVCProject.Models;
using MVCProject.Service;
using MVCProject.ViewModel;
using System;
using System.Linq;

namespace MVCProject.Controllers
{
    public class StudentController : Controller
    {
        public IStudentService StudentServices { get; }
        public ITrackService TrackServices { get; }
        public IInstructorService InstructorServices { get; }
        public IStdWithCrService IStdWithCrService { get; }
        public UserManager<IdentityUser> UserManager { get; }
        public SignInManager<IdentityUser> SignInManager { get; }
        public RoleManager<IdentityRole> RoleManager { get; }

        public StudentController(IStudentService _stdRepo,
            ITrackService _trkRepo, IInstructorService _InstructorServices,
            IStdWithCrService _IStdWithCrService, UserManager<IdentityUser> _UserManager,
            SignInManager<IdentityUser> _SignInManager, RoleManager<IdentityRole> _RoleManager)
        {
            StudentServices = _stdRepo;
            TrackServices = _trkRepo;
            InstructorServices = _InstructorServices;
            IStdWithCrService = _IStdWithCrService;
            UserManager = _UserManager;
            SignInManager = _SignInManager;
            RoleManager = _RoleManager;
        }

        [Route("Students")]
        public IActionResult GetAll()
        {
            ViewData["Trs"] = TrackServices.GetAll();
            return View(StudentServices.GetAll());
        }

        // Student/GetById
        //[Route("Student/id:int")]
        public IActionResult GetById([FromRoute] int id)
        {
            ViewData["Trs"] = TrackServices.GetAll();
            ViewData["IStdWithCr"] = IStdWithCrService.GetAll();
            return View(StudentServices.GetById(id));
        }

        // Student/Create
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["listOfUser"] = UserManager.Users.Select(x => x.UserName).ToList();
            ViewData["Trs"] = TrackServices.GetAll();
            ViewData["insts"] = InstructorServices.GetAll();
            return View();
        }


        [HttpPost]
        public IActionResult Create(Student newstd)///Save not create -> create not save ya mayadaw
        {
            if (ModelState.IsValid)
            {
                //save db
                StudentServices.Create(newstd);
                //display index view
                return RedirectToAction("GetAll");
            }
            ViewData["Trs"] = TrackServices.GetAll();
            ViewData["insts"] = InstructorServices.GetAll();
            return View(newstd);//html
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewData["Trs"] = TrackServices.GetAll();
            ViewData["insts"] = InstructorServices.GetAll();
            Student std = StudentServices.GetById(id);
            return View(std);
        }
        [HttpPost]
        public IActionResult Update(Student newStudent)
        {
            if (ModelState.IsValid)
            {
                StudentServices.Update(newStudent);
                return RedirectToAction("GetAll");
            }
            ViewData["Trs"] = TrackServices.GetAll();
            ViewData["insts"] = InstructorServices.GetAll();
            return View(newStudent);
        }


        public IActionResult Delete([FromRoute] int id)
        {
            try
            {
                StudentServices.Delete(id);
                return RedirectToAction("GetAll");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.InnerException.Message);
                return View("Update");
            }
        }

        public IActionResult Exisit(string Name, int id)
        {
            Student std = StudentServices.GetByName(Name);
            //case Add New Student
            if (id == 0)
            {
                if (std == null)
                    return Json(true);
                return Json(false); //name exists
            }
            else  //edit
            {
                if (std == null)
                    return Json(true); //update name with new value not exist before
                else
                {
                    if (std.Id == id)
                        return Json(true); //update
                    return Json(false);
                }
            }
        }

        // Student/GetStudent
       
        public IActionResult GetStudent(int id)
        {
            StdWithCr crs = IStdWithCrService.Get(id);
            StudentWithCrsDegreeVM stdVM = new StudentWithCrsDegreeVM();
            stdVM.StudentName = crs.Student.Name;
            stdVM.CrsName = crs.Course.Name;
            stdVM.Degree = crs.Degree;
            stdVM.Id = crs.Id;
            return View(stdVM);
        }

        //public IActionResult getInstructors(int id)
        //{
        //    List<Instructor> instModel = StudentServices.GetAllInstById(id);
        //    return View("ShowAllInstructors", instModel);//connection betwen view with model
        //}
    }

}

MVCProject/Controllers/TrackController.cs
using Microsoft.AspNetCore.Mvc;
using MVCProject.Models;
using MVCProject.Service;
using System;

namespace pproject.Controllers
{
    public class TrackController : Controller
    {
        // injection
        public ITrackService TrackRepo { get; }
        public TrackController(ITrackService trackRepo)
        {
            TrackRepo = trackRepo;
        }

        // Track/GetAll
        [Route("Tracks")]
        public IActionResult GetAll()
        {
            return View(TrackRepo.GetAll());
        }

        public IActionResult GetById([FromRoute] int id)
        {
            return View(TrackRepo.GetById(id));
        }

        // Track/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Track Track)
        {
            if (!ModelState.IsValid)
            {
                TrackRepo.Create(Track);
                return RedirectToAction("GetAll");
            }
            return View(Track);
        }

        // Track/Update
        [HttpGet]
        public IActionResult Update([FromRoute] int id)
        {
            return View(TrackRepo.GetById(id));
        }

        [HttpPost]
        public IActionResult Update(Track track)
        {
            if (ModelState.IsValid)
            {
                TrackRepo.Update(track);
                return RedirectToAction("GetAll");
            }
            return View(track);
        }

        public IActionResult Delete([FromRoute] int id)
        {
            try
            {
                TrackRepo.Delete(id);
                return RedirectToAction("GetAll");
            }
            catch
            {
                ModelState.AddModelError("", "You cant delete this track");
                return View("ErrorPage");
            }
        }

        public IActionResult Exisit(int id, string Name)
        {
            var track = TrackRepo.GetByName(Name);
            if (id == 0)
            {
                if (track == null)
                    return Json(true);
                return Json(false);
            }
            else
            {
                if (track == null)
                    return Json(true);
                else
                {
                    if (id == track.Id)
                        return Json(true);
                    return Json(false);
                }
            }
        }
    }
}

MVCProject/Views/DashBoard/Index.cshtml
    <section id="courses" class="courses">
      <div class="container" data-aos="fade-up">

        <div class="row" data-aos="zoom-in" data-aos-delay="100">

          <div class="col-lg-4 col-md-6 d-flex align-items-start">
            <div class="course-item">
              <img src="~/assets/img/events-2.jpg" class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <a class="btn btn-primary" asp-action="GetAll" asp-controller="Student">Students</a>
                </div>
                <h3>Show Students Data</h3>
              </div>
            </div>
          </div> <!-- End Course Item-->

          <div class="col-lg-4 col-md-6 d-flex align-items-start">
            <div class="course-item">
              <img src="~/assets/img/events-1.jpg" class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <a class="btn btn-primary"asp-action="GetAll" asp-controller="Instructor">Instructors</a>
                </div>

                <h3>Show Instructors Data</h3>
              </div>
            </div>
          </div> <!-- End Course Item-->

          <div class="col-lg-4 col-md-6 d-flex align-items-start">
            <div class="course-item">
              <img src="~/assets/img/course-2.jpg" class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <a class="btn btn-primary" asp-action="GetAll" asp-controller="Course">Courses</a>
                </div>

                <h3>Show Courses Data</h3>
                </div>
            </div>
          </div>
        </div>

        <div class="row mt-5" data-aos="zoom-in" data-aos-delay="100">

          <div class="col-lg-4 col-md-6 d-flex align-items-start">
            <div class="course-item">
              <img src="~/assets/img/course-1.jpg" class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <a class="btn btn-primary"asp-action="GetAll" asp-controller="Track">Tracks</a>
                </div>
                <h3>Show Tracks Data</h3>
              </div>
            </div>
          </div> <!-- End Course Item-->

          <div class="col-lg-4 col-md-6 d-flex align-items-start">
            <div class="course-item">
              <img src="~/assets/img/about.jpg" class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <a class="btn btn-primary" asp-action="about" asp-controller="Home">About</a>
                </div>

                <h3>About our Team</h3>
              </div>
            </div>
          </div> <!-- End Course Item-->

          <div class="col-lg-4 col-md-6 d-flex align-items-start">
            <div class="course-item">
              <img src="~/assets/img/course-3.jpg" class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <a class="btn btn-primary" asp-action="contact" asp-controller="Home">Contact</a>
                </div>

                <h3>Contact us</h3>
                </div>
            </div>
          </div>
        </div>





         <!-- End Course Item-->
      </div>
    </section><!-- End Courses Section -->
<style>
    #footer {
    position: relative !important;
    }
</style>